### ISSUE TITLE
User Story 2: Se projektoversigt

### ISSUE THREAD

**Issue by ajoeili** [ajoeili/Eksamensprojekt#2]
Som projektleder vil jeg kunne se en oversigt over projektet, så jeg hurtigt kan få adgang til projektets detaljer og status.

**Acceptkriterier:**

- Brugeren ser en side med en oversigt over projektets navn, beskrivelse, startdato, slutdato, teammedlemmer, projektleder og estimeret tid. 
- Hvis der ikke er oprettet noget projekt endnu, skal en besked vises ("No project has been made yet").
- Oversigten opdateres automatisk, hvis projektet ændres.

**Tasks:** 

1. Backend:
- [x] Implementér endpoint til at hente projektdata fra databasen.
- [x] Udarbejd en service til at formatere eller beregne estimeret pris og arbejdsdage.

2. Frontend:
- [x] Design HTML side til visning af projektdetaljer.
- [x] Tilføj en meddelelse ("No project has been made yet") i tilfælde af tomt data.
- [x] Implementér styling for oversigtslayout.

3. Integration:
- [x] Forbind frontend med backend via Thymeleaf for at hente projektdata dynamisk.
- [x] Test med oprettede og tomme projekter for korrekt rendering.

4. Automatisk opdatering:
- [x] Implementér mekanisme til at opdatere oversigten dynamisk.
